var Message = {
    UnknownToken:'Unknown token',
    UnexpectedToken:'Unexpected token',
    UnexpectedString:'Unexpected string',
    IllegalReservedIdent:'Variables starting with __ are reserved',
    IllegalIdent:'Identifier can not start with numeric',
    IllegalIdentInitialize: 'Identifier has to be initialized',
    IllegalComment:'Illegal comment',
    IllegalBlock:'Block statement must have one statement at least',
    IllegalFor:'Illegal for statement',
    IllegalWhile:'Illegal while statement',
    IllegalIf:'Illegal if statement',
    IllegalContinue:'Continue statement can not have label',
    IllegalContinuePosition:'Continue statement have to be declared in iteration',
    IllegalBreak:'Break statement can not have label',
    IllegalBreakPosition:'Break statement have to be declared in iteration',
    IllegalReturn:'Return statement has to be contained in function',
    IllegalReturnArgument:'Return argument has to be one',
    IllegalRaise:'Illegal raise statement',
    IllegalRaiseArgument: 'Raise argument has to be one',
    IllegalExcept:'Illegal except statement',
    IllegalFinally:'Illegal finally statement',
    IllegalConditionalExpression:'Illegal conditional expression',
    IllegalIndentSize:'Indent size may be incorrect',
    IllegalArgument:'argument has to be identifier',
    IllegalArgumentList:'Arguments maybe includes newline',
    IllegalFunctionExpression:'Illegal function expression',
    IllegalPostfixIncrement:'Postfix increment operator is only for variable',
    IllegalPostfixDecrement:'Postfix decrement operator is only for variable',
    IllegalPrefixIncrement:'Prefix increment operator is only for variable',
    IllegalPrefixDecrement:'Prefix decrement operator is only for variable',
    IllegalMultiplicativeExpression:'Illegal multiplicative expression',
    IllegalShiftExpression:'Illegal shift expression',
    IllegalRelationalExpression:'Illegal relational expression',
    IllegalIsinstance:'arguments of isinstance build-in function has to be two',
    IllegalTypeof:'argument of type build-in function has to be one',
    ReferenceError: '{0} is not defined'
};